innopacks/panel/routes/web.php
<?php
/**
 * Copyright (c) Since 2024 InnoCMS - All Rights Reserved
 *
 * @link       https://www.innocms.com
 * @author     InnoCMS <team@innoshop.com>
 * @license    https://opensource.org/licenses/OSL-3.0 Open Software License (OSL 3.0)
 */

use Illuminate\Support\Facades\Route;
use InnoCMS\Panel\Controllers;

Route::get('login', [Controllers\LoginController::class, 'index'])->name('login.index');
Route::post('login', [Controllers\LoginController::class, 'store'])->name('login.store');

Route::middleware(['admin_auth:admin'])
    ->group(function () {
        Route::get('logout', [Controllers\LogoutController::class, 'index'])->name('logout.index');

        Route::get('/', [Controllers\DashboardController::class, 'index'])->name('dashboard.index');

        Route::get('/locale/{code}', [Controllers\LocaleController::class, 'switch'])->name('locale.switch');

        Route::resource('/articles', Controllers\ArticleController::class);
        Route::resource('/catalogs', Controllers\CatalogController::class);
        Route::resource('/pages', Controllers\PageController::class);
        Route::resource('/tags', Controllers\TagController::class);

        Route::get('/locales', [Controllers\LocaleController::class, 'index'])->name('locales.index');
        Route::post('/locales/install', [Controllers\LocaleController::class, 'install'])->name('locales.install');
        Route::get('/locales/{locale}/edit', [Controllers\LocaleController::class, 'edit'])->name('locales.edit');
        Route::put('/locales/{locale}', [Controllers\LocaleController::class, 'update'])->name('locales.update');
        Route::post('/locales/{code}/uninstall', [Controllers\LocaleController::class, 'uninstall'])->name('locales.uninstall');

        Route::get('/themes', [Controllers\ThemeController::class, 'index'])->name('themes.index');
        Route::put('/themes/{country}/active', [Controllers\ThemeController::class, 'enable'])->name('themes.active');
        Route::get('/themes/settings', [Controllers\ThemeController::class, 'settings'])->name('themes_settings.index');
        Route::put('/themes/settings', [Controllers\ThemeController::class, 'updateSettings'])->name('themes_settings.update');

        Route::get('/account', [Controllers\AccountController::class, 'index'])->name('account.index');
        Route::put('/account', [Controllers\AccountController::class, 'update'])->name('account.update');

        Route::get('/settings', [Controllers\SettingController::class, 'index'])->name('settings.index');
        Route::put('/settings', [Controllers\SettingController::class, 'update'])->name('settings.update');

        Route::resource('/admins', Controllers\AdminController::class);
        Route::put('/admins/{currency}/active', [Controllers\AdminController::class, 'active'])->name('admins.active');

        Route::resource('/roles', Controllers\RoleController::class);
    });

innopacks/panel/resources/views/articles/form.blade.php
@extends('panel::layouts.app')

@section('title', __('panel::menu.articles'))

@section('content')
  <div class="card h-min-600">
    <div class="card-body">
      <form class="needs-validation" novalidate
            action="{{ $article->id ? panel_route('articles.update', [$article->id]) : panel_route('articles.store') }}"
            method="POST">
        @csrf
        @method($article->id ? 'PUT' : 'POST')

        <ul class="nav nav-tabs mb-4" role="tablist">
          <li class="nav-item" role="presentation">
            <button class="nav-link active" data-bs-toggle="tab" data-bs-target="#tab-data" type="button">文章内容
            </button>
          </li>
          <li class="nav-item" role="presentation">
            <button class="nav-link" data-bs-toggle="tab" data-bs-target="#tab-info" type="button">其他信息</button>
          </li>
        </ul>

        <div class="tab-content">
          <div class="tab-pane fade show active" id="tab-data">
            <div class="accordion accordion-flush locales-accordion" id="data-locales">
              @foreach (locales() as $locale)
                @php($localeCode = $locale->code)
                @php($localeName = $locale->name)
                <div class="accordion-item">
                  <h2 class="accordion-header">
                    <button class="accordion-button {{ $loop->first ? '' : 'collapsed' }}" type="button"
                            data-bs-toggle="collapse" data-bs-target="#data-locale-{{ $localeCode }}"
                            aria-expanded="{{ $loop->first ? 'true' : 'false' }}"
                            aria-controls="data-locale-{{ $localeCode }}">
                      <div class="wh-20 me-2">
                        <img src="{{ image_origin($locale->image) }}" class="img-fluid">
                      </div>
                      {{ $localeName }}
                    </button>
                  </h2>
                  <div id="data-locale-{{ $localeCode }}"
                       class="accordion-collapse collapse {{ $loop->first ? 'show' : '' }}"
                       data-bs-parent="#data-locales">
                    <div class="accordion-body">
                      <input name="translations[{{$localeCode}}][locale]" value="{{$localeCode}}" class="d-none">

                      <x-panel-form-input title="标题" name="translations[{{$localeCode}}][title]"
                                          value="{{ old('translations.' . $localeCode . '.title', $article->translate($localeCode, 'title')) }}"
                                          required placeholder="标题"/>

                      <x-panel-form-rich-text title="内容" name="translations[{{$localeCode}}][content]"
                                              value="{{ old('translations.' . $localeCode . '.content', $article->translate($localeCode, 'content')) }}"
                                              required
                                              placeholder="内容"/>

                      <x-panel-form-textarea title="摘要" name="translations[{{$localeCode}}][summary]"
                                          value="{{ old('translations.' . $localeCode . '.summary', $article->translate($localeCode, 'summary')) }}"
                                          placeholder="摘要"/>

                      <x-panel-form-image title="主图" name="translations[{{$localeCode}}][image]"
                                          value="{{ old('translations.' . $localeCode . '.image', $article->translate($localeCode, 'image')) }}"
                                          placeholder="image"/>

                      <x-panel-form-input title="Meta Title" name="translations[{{$localeCode}}][meta_title]"
                                          value="{{ old('translations.' . $localeCode . '.meta_title', $article->translate($localeCode, 'meta_title')) }}"
                                          placeholder="Meta Title"/>

                      <x-panel-form-input title="Meta Keywords" name="translations[{{$localeCode}}][meta_keywords]"
                                          value="{{ old('translations.' . $localeCode . '.meta_keywords', $article->translate($localeCode, 'meta_keywords')) }}"
                                          placeholder="Meta Keywords"/>

                      <x-panel-form-input title="Meta Description" name="translations[{{$localeCode}}][meta_description]"
                                          value="{{ old('translations.' . $localeCode . '.meta_description', $article->translate($localeCode, 'meta_description')) }}"
                                          placeholder="Meta Description"/>
                    </div>
                  </div>
                </div>
              @endforeach
            </div>
          </div>

          <div class="tab-pane fade" id="tab-info">
            <x-panel-form-select title="分类" name="catalog_id" :value="old('catalog_id', $article->catalog_id ?? 0)"
                                :options="$catalogs" key="id" label="name" />
            <x-panel-form-input title="SEO 别名" name="slug" :value="old('slug', $article->slug ?? '')"
                                placeholder="SEO 别名" />

            <x-panel-form-autocomplete-list name="tag_ids[]" :value="old('tag_ids', $article->tags->pluck('id')->toArray() ?? [])"
              placeholder="请搜索标签" title="标签" api="/api/panel/tags" />

            <x-panel-form-input title="文章排序" name="position" :value="old('position', $article->position ?? 0)"
                                placeholder="文章排序"/>
            <x-panel-form-input title="浏览次数" name="viewed" :value="old('viewed', $article->viewed ?? 0)"
                                placeholder="浏览次数"/>
            <x-panel-form-input title="文章作者" name="author" :value="old('author', $article->author ?? '')"
                                placeholder="文章作者"/>
            <x-panel-form-switch-radio title="是否启用" name="active" :value="old('active', $article->active ?? true)"
                                placeholder="是否启用"/>
          </div>
        </div>

        <x-panel::form.bottom-btns />
      </form>
    </div>
  </div>
@endsection

@push('footer')
  <script>
  </script>
@endpush

innopacks/panel/resources/views/articles/index.blade.php
@extends('panel::layouts.app')
@section('body-class', 'page-home')

@section('title', __('panel::menu.articles'))

@section('content')
<div class="card h-min-600">
  <div class="card-body">
    <div class="d-flex justify-content-between mb-4">
      <a href="{{ panel_route('articles.create') }}" class="btn btn-primary"><i class="bi bi-plus-square"></i> 添加</a>
    </div>

    <table class="table">
      <thead>
        <tr>
          <td>ID</td>
          <td>图片</td>
          <td>标题</td>
          <td>分类</td>
          <td>标签</td>
          <td>SEO 别名</td>
          <td>操作</td>
        </tr>
      </thead>
      @if ($articles->count())
      <tbody>
        @foreach($articles as $item)
          <tr>
            <td>{{ $item->id }}</td>
            <td><img src="{{ image_resize($item->translation->image ?? '', 30, 30) }}" style="width: 30px; height: 30px" alt=""></td>
            <td>{{ sub_string($item->translation->title ?? '', 30) }}</td>
            <td>{{ $item->catalog->translation->title ?? '-' }}</td>
            <td>{{ $item->tagNames ?? '' }}</td>
            <td>{{ $item->slug }}</td>
            <td>
              <a href="{{ panel_route('articles.edit', [$item->id]) }}" class="btn btn-sm btn-outline-primary">编辑</a>
              <form action="{{ panel_route('articles.destroy', [$item->id]) }}" method="POST" class="d-inline">
                @csrf
                @method('DELETE')
                <button type="submit" class="btn btn-sm btn-outline-danger">删除</button>
              </form>
            </td>
          </tr>
        @endforeach
      </tbody>
      @else
      <tbody><tr><td colspan="5"><x-panel-no-data /></td></tr></tbody>
      @endif
    </table>
    {{ $articles->withQueryString()->links('panel::vendor/pagination/bootstrap-4') }}
  </div>
</div>
@endsection

@push('footer')
  <script>
  </script>
@endpush

innopacks/panel/resources/views/catalogs/form.blade.php
@extends('panel::layouts.app')

@section('title', __('panel::menu.catalogs'))

@section('content')
  <div class="card h-min-600">
    <div class="card-body">
      <form class="needs-validation" novalidate
            action="{{ $catalog->id ? panel_route('catalogs.update', [$catalog->id]) : panel_route('catalogs.store') }}"
            method="POST">
        @csrf
        @method($catalog->id ? 'PUT' : 'POST')

        <ul class="nav nav-tabs mb-4" role="tablist">
          <li class="nav-item" role="presentation">
            <button class="nav-link active" data-bs-toggle="tab" data-bs-target="#tab-data" type="button">分类内容
            </button>
          </li>
          <li class="nav-item" role="presentation">
            <button class="nav-link" data-bs-toggle="tab" data-bs-target="#tab-info" type="button">其他信息</button>
          </li>
        </ul>

        <div class="tab-content">
          <div class="tab-pane fade show active" id="tab-data">
            <div class="accordion accordion-flush locales-accordion" id="data-locales">
              @foreach (locales() as $locale)
                @php($localeCode = $locale->code)
                @php($localeName = $locale->name)
                <div class="accordion-item">
                  <h2 class="accordion-header">
                    <button class="accordion-button {{ $loop->first ? '' : 'collapsed' }}" type="button"
                            data-bs-toggle="collapse" data-bs-target="#data-locale-{{ $localeCode }}"
                            aria-expanded="{{ $loop->first ? 'true' : 'false' }}"
                            aria-controls="data-locale-{{ $localeCode }}">
                      <div class="wh-20 me-2">
                        <img src="{{ image_origin($locale->image) }}" class="img-fluid">
                      </div>
                      {{ $localeName }}
                    </button>
                  </h2>
                  <div id="data-locale-{{ $localeCode }}"
                       class="accordion-collapse collapse {{ $loop->first ? 'show' : '' }}"
                       data-bs-parent="#data-locales">
                    <div class="accordion-body">
                      <input name="translations[{{$localeCode}}][locale]" value="{{$localeCode}}" class="d-none">

                      <x-panel-form-input title="标题" name="translations[{{$localeCode}}][title]"
                                          value="{{ old('translations.' . $localeCode . '.title', $catalog->translate($localeCode, 'title')) }}"
                                          required placeholder="标题"/>

                      <x-panel-form-input title="摘要说明" name="translations[{{$localeCode}}][summary]"
                                          value="{{ old('translations.' . $localeCode . '.summary', $catalog->translate($localeCode, 'summary')) }}"
                                          placeholder="摘要说明"/>

                      <x-panel-form-input title="Meta Title" name="translations[{{$localeCode}}][meta_title]"
                                          value="{{ old('translations.' . $localeCode . '.meta_title', $catalog->translate($localeCode, 'meta_title')) }}"
                                          placeholder="Meta Title"/>

                      <x-panel-form-input title="Meta Keywords" name="translations[{{$localeCode}}][meta_keywords]"
                                          value="{{ old('translations.' . $localeCode . '.meta_keywords', $catalog->translate($localeCode, 'meta_keywords')) }}"
                                          placeholder="Meta Keywords"/>

                      <x-panel-form-input title="Meta Description" name="translations[{{$localeCode}}][meta_description]"
                                          value="{{ old('translations.' . $localeCode . '.meta_description', $catalog->translate($localeCode, 'meta_description')) }}"
                                          placeholder="Meta Description"/>
                    </div>
                  </div>
                </div>
              @endforeach
            </div>
          </div>

          <div class="tab-pane fade" id="tab-info">
            <x-panel-form-select title="上级分类" name="parent_id" :value="old('parent_id', $catalog->parent_id ?? 0)"
                                :options="$catalogs" key="id" label="name" />
            <x-panel-form-input title="SEO 别名" name="slug" :value="old('slug', $catalog->slug ?? '')"
                                placeholder="SEO 别名" />
            <x-panel-form-input title="分类排序" name="position" :value="old('position', $catalog->position ?? 0)"
                                placeholder="文章排序"/>
            <x-panel-form-switch-radio title="是否启用" name="active" :value="old('active', $catalog->active ?? true)"
              placeholder="是否启用"/>
          </div>
        </div>

        <x-panel::form.bottom-btns />
      </form>
    </div>
  </div>
@endsection

@push('footer')
  <script>
  </script>
@endpush

innopacks/panel/resources/views/catalogs/index.blade.php
@extends('panel::layouts.app')
@section('body-class', 'page-home')

@section('title', __('panel::menu.catalogs'))

@section('content')
  <div class="card h-min-600">
    <div class="card-body">
      <div class="d-flex justify-content-between mb-4">
        <a href="{{ panel_route('catalogs.create') }}" class="btn btn-primary"><i class="bi bi-plus-square"></i>
          添加</a>
      </div>
      <table class="table">
        <thead>
        <tr>
          <td>ID</td>
          <td>分类名称</td>
          <td>上级分类</td>
          <td>SEO 别名</td>
          <td>排序</td>
          <td>启用</td>
          <td>操作</td>
        </tr>
        </thead>
        @if ($catalogs->count())
          <tbody>
          @foreach($catalogs as $item)
            <tr>
              <td>{{ $item->id }}</td>
              <td>{{ $item->translation->title ?? '' }}</td>
              <td>{{ $item->parent->translation->title ?? '-' }}</td>
              <td>{{ $item->slug }}</td>
              <td>{{ $item->position }}</td>
              <td>{{ $item->active }}</td>
              <td>
                <a href="{{ panel_route('catalogs.edit', [$item->id]) }}"
                   class="btn btn-sm btn-outline-primary">编辑</a>
                <form action="{{ panel_route('catalogs.destroy', [$item->id]) }}" method="POST" class="d-inline">
                  @csrf
                  @method('DELETE')
                  <button type="submit" class="btn btn-sm btn-outline-danger">删除</button>
                </form>
              </td>
            </tr>
          @endforeach
          </tbody>
        @else
          <tbody>
          <tr>
            <td colspan="5">
              <div class="d-flex align-items-center flex-column py-4">
                <img src="{{ asset('images/no-data.svg') }}" class="img-fluid wp-400">
                <span class="fs-4 text-secondary">没有数据 ~</span>
              </div>
            </td>
          </tr>
          </tbody>
        @endif
      </table>
      {{ $catalogs->withQueryString()->links('panel::vendor/pagination/bootstrap-4') }}
    </div>
  </div>
@endsection

@push('footer')
  <script>
  </script>
@endpush

innopacks/panel/resources/views/settings/index.blade.php
@extends('panel::layouts.app')
@section('body-class', 'page-home')

@section('title', '系统设置')

<x-panel::form.right-btns />

@section('content')
  <div class="card h-min-600">
    <div class="card-body">
      <form class="needs-validation" id="app-form" novalidate action="{{ panel_route('settings.update') }}" method="POST">
        @csrf
        @method('put')

        <x-panel-form-image title="前台 Logo" name="front_logo" value="{{ old('front_logo', system_setting('front_logo')) }}"/>

        <x-panel-form-image title="后台 Logo" name="panel_logo" value="{{ old('panel_logo', system_setting('panel_logo')) }}"/>

        <x-panel-form-image title="缺省图" name="placeholder" value="{{ old('placeholder', system_setting('placeholder')) }}"/>

        <x-panel-form-image title="浏览器小图标" name="favicon" value="{{ old('favicon', system_setting('favicon')) }}"/>

        <x-panel-form-input title="Meta 标题" name="meta_title"
                            value="{{ old('meta_title', system_setting('meta_title')) }}" required
                            placeholder="Meta 标题"/>

        <x-panel-form-input title="Meta 关键词" name="meta_keywords"
                            value="{{ old('meta_keywords', system_setting('meta_keywords')) }}"
                            placeholder="Meta 关键词"/>

        <x-panel-form-textarea title="Meta 描述" name="meta_description"
                               value="{{ old('meta_description', system_setting('meta_description')) }}"
                               placeholder="Meta 描述"/>

        <x-panel-form-switch-radio title="启用 html 后缀" name="has_suffix" :value="old('has_suffix', system_setting('has_suffix', 0))"
                                   placeholder="启用 html 后缀"/>

        <x-panel-form-input title="ICP备案号" name="icp_number" value="{{ old('icp_number', system_setting('icp_number')) }}"/>

        <x-panel-form-textarea title="第三方JS代码" name="js_code"
                               value="{{ old('js_code', system_setting('js_code')) }}"
                               placeholder="第三方JS代码"/>

        <button type="submit" class="d-none"></button>
      </form>
    </div>
  </div>
@endsection

@push('footer')
  <script>
  </script>
@endpush

innopacks/panel/resources/views/shared/list_switch.blade.php
<div class="form-check form-switch list-switch" data-url="{{ $url }}" data-reload="{{ $reload ?? false }}">
  <input class="form-check-input" type="checkbox" role="switch" @if($value) checked @endif >
</div>

@pushOnce('footer')
  <script>
    $(function () {
      $('.list-switch > input[role="switch"]').on('change', function () {
        let status = $(this).prop('checked') ? 1 : 0;
        let url = $(this).parent().data('url');
        let reload = $(this).parent().data('reload');

        layer.load(2, {shade: [0.3,'#fff'] })
        axios.put(url, {status}).then((res) => {
          inno.msg(res.message)
          if (reload) {
            location.reload();
          }
        }).catch((err) => {
          $(this).prop('checked', !status);
          inno.msg(err.response.data.message)
        }).finally(() => {
          layer.closeAll('loading');
        });
      });
    });
  </script>
@endPushOnce

innopacks/panel/resources/views/themes/index.blade.php
@extends('panel::layouts.app')
@section('body-class', 'theme')

@section('title', __('panel::menu.themes'))

@section('content')
  <div class="card h-min-600">
    <div class="card-body">
      @if($themes)
        <div class="themes-wrap">
          <div class="row">
            @foreach($themes as $theme)
              <div class="col-6 col-lg-4 mb-3">
                <div class="themes-item border rounded-3 overflow-hidden">
                  <div class="image border-bottom"><img src="{{ theme_asset($theme['code'],'images/preview.jpg') }}" class="img-fluid"></div>
                  <div class="d-flex justify-content-between align-items-center p-3">
                    <span class="fw-bold">{{ $theme['name'] }}</span>
                    <span>@include('panel::shared.list_switch', ['value' => $theme['value'] ?? 0, 'url' => panel_route('themes.active', $theme['code']), 'reload' => true])</span>
                  </div>
                </div>
              </div>
            @endforeach
          </div>
        </div>
      @else
        <x-common-no-data :text="__('panel::themes.no_custom_theme')" />
      @endif
    </div>
  </div>
@endsection