innopacks/plugin/routes/web.php
<?php
/**
 * Copyright (c) Since 2024 InnoShop - All Rights Reserved
 *
 * @link       https://www.innoshop.com
 * @author     InnoShop <team@innoshop.com>
 * @license    https://opensource.org/licenses/OSL-3.0 Open Software License (OSL 3.0)
 */

use Illuminate\Support\Facades\Route;
use InnoShop\Plugin\Controllers\PluginController;

Route::resource('/plugins', PluginController::class);
Route::post('/plugins/enabled', [PluginController::class, 'updateStatus'])->name('plugins.update_status');

innopacks/plugin/resources/views/plugins/error.blade.php
@extends('panel::layouts.app')

@section('title', '插件详情')

@section('content')
  <div class="card h-min-600">
    <div class="card-body">
      <h6 class="border-bottom pb-3 mb-4">Error</h6>

      @if (session()->has('errors'))
        <x-common-alert type="danger" msg="{{ session('errors')->first() }}" class="mt-4"/>
      @endif

      @if (session('success'))
        <x-common-alert type="success" msg="{{ session('success') }}" class="mt-4"/>
      @endif

      {{ $error }}

    </div>
  </div>
@endsection

@push('footer')
  <script></script>
@endpush

innopacks/plugin/resources/views/plugins/form.blade.php
@extends('panel::layouts.app')

@section('title', __('panel::menu.plugins'))

<x-panel::form.right-btns />

@section('content')
<div class="card h-min-600">
  <div class="card-body">
    <h6 class="border-bottom pb-3 mb-4">{{ $plugin->getLocaleName() }}</h6>

    <form class="needs-validation" id="app-form" novalidate action="{{ panel_route('plugins.update', [$plugin->getCode()]) }}" method="POST">
      @csrf
      {{ method_field('put') }}
      <div class="row">
        <div class="col-12 col-md-7">
          @foreach ($fields as $field)
            @if ($field['type'] == 'image')
              <x-common-form-image
                :name="$field['name']"
                :title="$field['label']"
                :description="$field['description'] ?? ''"
                :error="$errors->first($field['name'])"
                :required="(bool)$field['required']"
                :value="old($field['name'], $field['value'] ?? '')">
                @if ($field['recommend_size'] ?? false)
                <div class="help-text font-size-12 lh-base">{{ __('common.recommend_size') }} {{ $field['recommend_size'] }}</div>
                @endif
              </x-common-form-image>
            @endif

            @if ($field['type'] == 'string')
              <x-common-form-input
                :name="$field['name']"
                :title="$field['label']"
                :placeholder="$field['placeholder'] ?? ''"
                :description="$field['description'] ?? ''"
                :error="$errors->first($field['name'])"
                :required="(bool)$field['required']"
                :value="old($field['name'], $field['value'] ?? '')" />
            @endif

            @if ($field['type'] == 'multi-string')
              <x-common-form-input
                :name="$field['name']"
                :title="$field['label']"
                :placeholder="$field['placeholder'] ?? ''"
                :description="$field['description'] ?? ''"
                :error="$errors->first($field['name'])"
                :required="(bool)$field['required']"
                :is-locales="true"
                :value="old($field['name'], $field['value'] ?? '')" />
            @endif

            @if ($field['type'] == 'select')
              <x-common-form-select
                :name="$field['name']"
                :title="$field['label']"
                :value="old($field['name'], $field['value'] ?? '')"
                :options="$field['options']">
                @if (isset($field['description']))
                  <div class="help-text font-size-12 lh-base">{{ $field['description'] }}</div>
                @endif
              </x-common-form-select>
            @endif

            @if ($field['type'] == 'bool')
              <x-common-form-switch-radio
                :name="$field['name']"
                :title="$field['label']"
                :value="old($field['name'], $field['value'] ?? '')">
                @if (isset($field['description']))
                  <div class="help-text font-size-12 lh-base">{{ $field['description'] }}</div>
                @endif
              </x-common-form-switch-radio>
            @endif

            @if ($field['type'] == 'textarea')
              <x-common-form-textarea
                :name="$field['name']"
                :title="$field['label']"
                :required="(bool)$field['required']"
                :value="old($field['name'], $field['value'] ?? '')">
                @if (isset($field['description']))
                  <div class="help-text font-size-12 lh-base">{{ $field['description'] }}</div>
                @endif
              </x-common-form-textarea>
            @endif

            @if ($field['type'] == 'multi-textarea')
              <x-common-form-textarea
                :name="$field['name']"
                :title="$field['label']"
                :required="(bool)$field['required']"
                :is-locales="true"
                :value="old($field['name'], $field['value'] ?? '')">
                @if (isset($field['description']))
                  <div class="help-text font-size-12 lh-base">{{ $field['description'] }}</div>
                @endif
              </x-common-form-textarea>
            @endif

            @if ($field['type'] == 'rich-text')
              <x-common-form-rich-text
                :name="$field['name']"
                :title="$field['label']"
                :value="old($field['name'], $field['value'] ?? '')"
                :required="(bool)$field['required']"
                >
                @if (isset($field['description']))
                  <div class="help-text font-size-12 lh-base">{{ $field['description'] }}</div>
                @endif
              </x-common-form-rich-text>
            @endif

            @if ($field['type'] == 'multi-rich-text')
              <x-common-form-rich-text
                :name="$field['name']"
                :title="$field['label']"
                :value="old($field['name'], $field['value'] ?? '')"
                :required="(bool)$field['required']"
                :is-locales="true"
                >
                @if (isset($field['description']))
                  <div class="help-text font-size-12 lh-base">{{ $field['description'] }}</div>
                @endif
              </x-common-form-rich-text>
            @endif

            @if ($field['type'] == 'checkbox')
              <x-panel::form.row :title="$field['label']" :required="(bool)$field['required']">
                <div class="form-checkbox">
                  @foreach ($field['options'] as $item)
                  <div class="form-check d-inline-block mt-2 me-3">
                    <input
                      class="form-check-input"
                      name="{{ $field['name'] }}[]"
                      type="checkbox"
                      value="{{ old($field['name'], $item['value']) }}"
                      {{ in_array($item['value'], old($field['name'], json_decode($field['value'] ?? '[]', true))) ? 'checked' : '' }}
                      id="flexCheck-{{ $field['name'] }}-{{ $loop->index }}">
                    <label class="form-check-label" for="flexCheck-{{ $field['name'] }}-{{ $loop->index }}">
                      {{ $item['label'] }}
                    </label>
                  </div>
                  @endforeach
                </div>
                @if (isset($field['description']))
                  <div class="help-text font-size-12 lh-base">{{ $field['description'] }}</div>
                @endif
              </x-panel::form.row>
            @endif
          @endforeach
        </div>
      </div>
    </form>
  </div>
</div>
@endsection

@push('footer')
  <script></script>
@endpush

innopacks/plugin/resources/views/plugins/index.blade.php
@extends('panel::layouts.app')
@section('body-class', 'page-my-plugins')

@section('title', __('panel::menu.plugins'))

@section('content')
<div class="card h-min-600">
  <div class="card-header">{{ __('panel::menu.plugins') }}</div>

  <div class="card-body">

    <div class="row">
      @foreach ($plugins as $plugin)
      <div class="col-6 col-lg-3 mb-4">
        <div class="plugin-item" data-code="{{ $plugin['code'] }}" data-installed="{{ $plugin['installed'] ? 1 : 0 }}">
          <div class="image-wrap">
            <div class="image"><img src="{{ $plugin['icon'] }}" alt="{{ $plugin['name'] }}" class="img-fluid"></div>
            <div class="title">{{ $plugin['name'] }}</div>
          </div>

          <div class="plugin-info">
            <div class="description">{{ $plugin['description'] }}</div>
            <div class="d-flex justify-content-between align-items-center">
              <div class="version">
                <div class="d-flex align-items-center">
                  <div class="form-switch plugin-enabled-switch cursor-pointer">
                    <input class="form-check-input" type="checkbox" {{ !$plugin['installed'] ? 'disabled' : '' }} role="switch" {{ $plugin['enabled'] ? 'checked' : '' }}>
                  </div>
                </div>
              </div>
              <div class="btns">
                @if ($plugin['installed'])
                  <a href="{{ $plugin['edit_url'] }}" class="btn btn-primary btn-sm">{{ __('panel::common.edit') }}</a>
                  <div class="btn btn-danger btn-sm uninstall-plugin">{{ __('panel::common.uninstall') }}</div>
                  @else
                  <div class="btn btn-primary btn-sm install-plugin">{{ __('panel::common.install') }}</div>
                @endif
              </div>
            </div>
          </div>
        </div>
      </div>
      @endforeach
    </div>
  </div>
</div>
@endsection

@push('footer')
  <script>
    $(function() {
      $('.install-plugin').click(function() {
        var code = $(this).parents('.plugin-item').data('code');
        pluginsUpdata(code, 'install');
      });

      $('.uninstall-plugin').click(function() {
        var code = $(this).parents('.plugin-item').data('code');
        pluginsUpdata(code, 'uninstall');
      });
    });

    $('.plugin-enabled-switch input').change(function() {
      const self = $(this);
      var code = $(this).parents('.plugin-item').data('code');
      var enabled = $(this).prop('checked') ? 1 : 0;
      axios.post('/panel/plugins/enabled', { code: code, enabled: enabled }).then(function(res) {
        if (res.success) {
          window.location.reload();
        } else {
          layer.msg(res.message);
        }
      }).catch(function(error) {
        layer.msg(error.response.data.message);
        self.prop('checked', !enabled);
      });
    });

    function pluginsUpdata(code, type) {
      const url = type === 'install' ? '/panel/plugins' : '/panel/plugins/' + code;
      const method = type === 'install' ? 'post' : 'delete';

      axios[method](url, { code: code }).then(function(res) {
        if (res.success) {
          window.location.reload();
        } else {
          layer.msg(res.message);
        }
      });
    }
  </script>
@endpush